### ISSUE TITLE
Exception: Invalid key

### ISSUE THREAD

**Issue by Strykar** [RustyBower/sopel-weather#12]
In the bot config I've defined:
```
[weather]
geocoords_provider = openweathermap
geocoords_api_key = my_key
weather_provider = openweathermap
weather_api_key = my_key
```

When I try to `.weather 90210`, I get:
```
[2020-07-06 17:45:52,487] sopel.bot            ERROR    - Unexpected error (Invalid key) from Strykar at 2020-07-06 17:45:52.487109. Message was: .weather 90210
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sopel/bot.py", line 606, in call
    exit_code = func(sopel, trigger)
  File "/usr/lib/python3.8/site-packages/sopel_modules/weather/weather.py", line 234, in weather_command
    data = get_weather(bot, trigger)
  File "/usr/lib/python3.8/site-packages/sopel_modules/weather/weather.py", line 197, in get_weather
    latitude, longitude, location = get_geocoords(bot, trigger)
  File "/usr/lib/python3.8/site-packages/sopel_modules/weather/weather.py", line 141, in get_geocoords
    raise Exception(r.json()['error'])
```
I generated a new API key to be sure, and the error persists, what am I missing?

**Comment by RustyBower** [comment]
Per the documentation (https://github.com/RustyBower/sopel-weather#api-keys), you'll need a LocationIQ API key and that is what goes in place of geocoords_provider, which you can see referenced https://github.com/RustyBower/sopel-weather/blob/master/sopel_modules/weather/weather.py#L27. Technically, you just need to define the geocoords_api_key from LocationIQ, since it's the default provider, but there you go.
